import { spyOn, test } from 'bun:test'
import assert from 'node:assert/strict'

import { hashPassword, verifyPassword } from '../src/services/localPassword'

test('hashes a password into bcrypt format', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.match(hash, /^\$2[aby]\$/)
})

test('verifies a password it just hashed', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.equal(await verifyPassword('correct horse battery staple', hash), true)
})

test('rejects a wrong password', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.equal(await verifyPassword('Tr0ub4dor&3', hash), false)
})

test('verifies a hash produced by the previous bcrypt library', async () => {
  // Generated by bcrypt@5.1.1 with cost 10 for the password "reactmap".
  const legacy = '$2b$10$aOiX/0v15RWQPR8q9hXl3.Z7HQgEYwBbkaoDSISoTqMcdwOcfvUPa'
  assert.equal(await verifyPassword('reactmap', legacy), true)
})

test('does not truncate passwords at 72 bytes', async () => {
  // bcrypt@5 silently truncated at 72 bytes, so 'a' * 73 and 'a' * 100 shared a
  // hash. Bun pre-hashes longer passwords instead, keeping every byte
  // significant. Guards against a regression to truncating behaviour.
  const hash = await hashPassword('a'.repeat(73))
  assert.equal(await verifyPassword('a'.repeat(73), hash), true)
  assert.equal(await verifyPassword('a'.repeat(72), hash), false)
  assert.equal(await verifyPassword('a'.repeat(100), hash), false)
})

// Fixtures below were generated by bcrypt@5.1.1 at cost 10 against the full
// password. bcrypt truncated at 72 bytes, so each hash encodes only that
// prefix, exactly as a row written before the Bun.password migration does.
const LEGACY_LONG_PASSWORD =
  'correct horse battery staple correct horse battery staple correct horse battery staple'
const LEGACY_LONG_HASH =
  '$2b$10$bx0gF1HY8Okg/KBBlwqtBOox.irY5bqaTEkR.OW8E8Xx3FRG8v.OS'

// 39 characters, 100 bytes. Byte 72 lands in the middle of a 3-byte 日, so a
// character-boundary slice and a lossy re-encode both produce different bytes
// than bcrypt saw.
const LEGACY_MULTIBYTE_PASSWORD = `p@sswörd-${'日'.repeat(30)}`
const LEGACY_MULTIBYTE_HASH =
  '$2b$10$bo6ga7lhKno/p//bkO6Bruz1JO2dJsHBjX0.AUWsnYkKRDWrUcAa6'

test('verifies a password longer than 72 bytes against its legacy hash', async () => {
  assert.equal(
    await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH),
    true,
  )
})

test('does not rewrite the row for a login with a different tail', async () => {
  // The bytes past 72 were never verified against anything, so a mistyped tail
  // reaches this path looking exactly like the real one. Re-hashing the
  // submitted string would make the mistyped password canonical and lock the
  // owner out. The stored hash has to survive untouched -- verifyPassword
  // itself never writes anywhere, so "untouched" here means its return value
  // stays derived purely from the hash it was given, not from a side effect.
  const mistyped = `${LEGACY_LONG_PASSWORD.slice(0, 72)}totally different tail`
  assert.equal(Buffer.byteLength(mistyped, 'utf8') > 72, true)
  assert.notEqual(mistyped, LEGACY_LONG_PASSWORD)

  assert.equal(await verifyPassword(mistyped, LEGACY_LONG_HASH), true)

  // The real password still works, because nothing was written.
  assert.equal(
    await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH),
    true,
  )
})

test('keeps accepting the legacy prefix on every login', async () => {
  // Without the rewrite this path never converges, so it has to stay repeatable
  // rather than working once.
  for (let i = 0; i < 3; ++i) {
    assert.equal(
      await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH),
      true,
    )
  }
})

test('rejects a wrong password longer than 72 bytes', async () => {
  const wrong = `wrong ${LEGACY_LONG_PASSWORD}`
  assert.equal(Buffer.byteLength(wrong, 'utf8') > 72, true)

  assert.equal(await verifyPassword(wrong, LEGACY_LONG_HASH), false)
})

test('truncates on the byte boundary, not the character boundary', async () => {
  // Under 72 characters, so a length check would never reach the fallback.
  assert.equal(LEGACY_MULTIBYTE_PASSWORD.length < 72, true)
  assert.equal(Buffer.byteLength(LEGACY_MULTIBYTE_PASSWORD, 'utf8'), 100)

  assert.equal(
    await verifyPassword(LEGACY_MULTIBYTE_PASSWORD, LEGACY_MULTIBYTE_HASH),
    true,
  )
})

test('does not fall back for a hash written by Bun', async () => {
  const hash = await hashPassword(LEGACY_LONG_PASSWORD)

  assert.equal(
    await verifyPassword(`${LEGACY_LONG_PASSWORD} extra`, hash),
    false,
  )

  const spy = spyOn(Bun.password, 'verify')
  try {
    assert.equal(await verifyPassword(LEGACY_LONG_PASSWORD, hash), true)
    assert.equal(spy.mock.calls.length, 1)
  } finally {
    spy.mockRestore()
  }
})

test('rejects a malformed stored hash instead of throwing', async () => {
  // bcrypt.compareSync returned false for these. Bun.password.verify throws,
  // and the throw escapes to a catch that never calls done, hanging the
  // request. Every row must resolve to a plain false.
  assert.equal(await verifyPassword('reactmap', 'not-a-hash-at-all'), false)
  assert.equal(await verifyPassword('reactmap', ''), false)
  assert.equal(
    await verifyPassword('reactmap', '$2b$10$tooshorttobeabcrypthash'),
    false,
  )
  // Discord and Telegram rows have no password at all.
  assert.equal(await verifyPassword('reactmap', null), false)
})

test('rejects a malformed stored hash for a password over 72 bytes', async () => {
  // The truncation fallback verifies a second time, so it needs the same guard.
  assert.equal(
    await verifyPassword(LEGACY_LONG_PASSWORD, 'not-a-hash-at-all'),
    false,
  )
})
