const assert = require('node:assert/strict')
const { test, spyOn } = require('bun:test')

const { state } = require('./stateMock')
const { hashPassword, verifyPassword } = require('../src/services/LocalClient')

test('hashes a password into bcrypt format', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.match(hash, /^\$2[aby]\$/)
})

test('verifies a password it just hashed', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.equal(await verifyPassword('correct horse battery staple', hash), true)
})

test('rejects a wrong password', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.equal(await verifyPassword('Tr0ub4dor&3', hash), false)
})

test('verifies a hash produced by the previous bcrypt library', async () => {
  // Generated by bcrypt@5.1.1 with cost 10 for the password "reactmap".
  const legacy = '$2b$10$aOiX/0v15RWQPR8q9hXl3.Z7HQgEYwBbkaoDSISoTqMcdwOcfvUPa'
  assert.equal(await verifyPassword('reactmap', legacy), true)
})

test('does not truncate passwords at 72 bytes', async () => {
  // bcrypt@5 silently truncated at 72 bytes, so 'a' * 73 and 'a' * 100 shared a
  // hash. Bun pre-hashes longer passwords instead, keeping every byte
  // significant. Guards against a regression to truncating behaviour.
  const hash = await hashPassword('a'.repeat(73))
  assert.equal(await verifyPassword('a'.repeat(73), hash), true)
  assert.equal(await verifyPassword('a'.repeat(72), hash), false)
  assert.equal(await verifyPassword('a'.repeat(100), hash), false)
})

// Fixtures below were generated by bcrypt@5.1.1 at cost 10 against the full
// password. bcrypt truncated at 72 bytes, so each hash encodes only that
// prefix, exactly as a row written before the Bun.password migration does.
const LEGACY_LONG_PASSWORD =
  'correct horse battery staple correct horse battery staple correct horse battery staple'
const LEGACY_LONG_HASH =
  '$2b$10$bx0gF1HY8Okg/KBBlwqtBOox.irY5bqaTEkR.OW8E8Xx3FRG8v.OS'

// 39 characters, 100 bytes. Byte 72 lands in the middle of a 3-byte 日, so a
// character-boundary slice and a lossy re-encode both produce different bytes
// than bcrypt saw.
const LEGACY_MULTIBYTE_PASSWORD = `p@sswörd-${'日'.repeat(30)}`
const LEGACY_MULTIBYTE_HASH =
  '$2b$10$bo6ga7lhKno/p//bkO6Bruz1JO2dJsHBjX0.AUWsnYkKRDWrUcAa6'

/**
 * Records every write the self-heal makes so tests can assert on it.
 * @returns {{patch: object, column: string, value: unknown}[]}
 */
function trackUserUpdates() {
  /** @type {{patch: object, column: string, value: unknown}[]} */
  const updates = []
  state.db.models.User = {
    query: () => ({
      update: (patch) => ({
        where: (column, value) => {
          updates.push({ patch, column, value })
          return Promise.resolve(1)
        },
      }),
    }),
  }
  return updates
}

test('verifies a password longer than 72 bytes against its legacy hash', async () => {
  trackUserUpdates()
  assert.equal(
    await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH, 7),
    true,
  )
})

test('re-hashes the full password after a legacy verify', async () => {
  const updates = trackUserUpdates()

  await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH, 7)

  assert.equal(updates.length, 1)
  assert.equal(updates[0].column, 'id')
  assert.equal(updates[0].value, 7)
  assert.match(updates[0].patch.password, /^\$2[aby]\$10\$/)
  assert.notEqual(updates[0].patch.password, LEGACY_LONG_HASH)
  // The replacement covers every byte, not just the first 72.
  assert.equal(
    await Bun.password.verify(LEGACY_LONG_PASSWORD, updates[0].patch.password),
    true,
  )
  assert.equal(
    await Bun.password.verify(
      LEGACY_LONG_PASSWORD.slice(0, 72),
      updates[0].patch.password,
    ),
    false,
  )
})

test('takes the fast path once the hash has been upgraded', async () => {
  const updates = trackUserUpdates()
  await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH, 7)
  const upgraded = updates[0].patch.password

  const spy = spyOn(Bun.password, 'verify')
  try {
    assert.equal(await verifyPassword(LEGACY_LONG_PASSWORD, upgraded, 7), true)
    // One call means the first verify succeeded and no fallback was attempted.
    assert.equal(spy.mock.calls.length, 1)
  } finally {
    spy.mockRestore()
  }
  // And no second row rewrite.
  assert.equal(updates.length, 1)
})

test('rejects a wrong password longer than 72 bytes', async () => {
  const updates = trackUserUpdates()
  const wrong = `wrong ${LEGACY_LONG_PASSWORD}`
  assert.equal(Buffer.byteLength(wrong, 'utf8') > 72, true)

  assert.equal(await verifyPassword(wrong, LEGACY_LONG_HASH, 7), false)
  assert.equal(updates.length, 0)
})

test('truncates on the byte boundary, not the character boundary', async () => {
  const updates = trackUserUpdates()
  // Under 72 characters, so a length check would never reach the fallback.
  assert.equal(LEGACY_MULTIBYTE_PASSWORD.length < 72, true)
  assert.equal(Buffer.byteLength(LEGACY_MULTIBYTE_PASSWORD, 'utf8'), 100)

  assert.equal(
    await verifyPassword(LEGACY_MULTIBYTE_PASSWORD, LEGACY_MULTIBYTE_HASH, 12),
    true,
  )
  assert.equal(updates.length, 1)
  assert.equal(updates[0].value, 12)
})

test('does not fall back for a hash written by Bun', async () => {
  const updates = trackUserUpdates()
  const hash = await hashPassword(LEGACY_LONG_PASSWORD)

  assert.equal(
    await verifyPassword(`${LEGACY_LONG_PASSWORD} extra`, hash, 7),
    false,
  )
  assert.equal(updates.length, 0)

  const spy = spyOn(Bun.password, 'verify')
  try {
    assert.equal(await verifyPassword(LEGACY_LONG_PASSWORD, hash, 7), true)
    assert.equal(spy.mock.calls.length, 1)
  } finally {
    spy.mockRestore()
  }
  assert.equal(updates.length, 0)
})

test('accepts a legacy verify when no user id is available', async () => {
  const updates = trackUserUpdates()
  assert.equal(
    await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH),
    true,
  )
  assert.equal(updates.length, 0)
})
