const assert = require('node:assert/strict')
const { test, spyOn } = require('bun:test')

const { state } = require('./stateMock')
const { hashPassword, verifyPassword } = require('../src/services/LocalClient')

test('hashes a password into bcrypt format', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.match(hash, /^\$2[aby]\$/)
})

test('verifies a password it just hashed', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.equal(await verifyPassword('correct horse battery staple', hash), true)
})

test('rejects a wrong password', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.equal(await verifyPassword('Tr0ub4dor&3', hash), false)
})

test('verifies a hash produced by the previous bcrypt library', async () => {
  // Generated by bcrypt@5.1.1 with cost 10 for the password "reactmap".
  const legacy = '$2b$10$aOiX/0v15RWQPR8q9hXl3.Z7HQgEYwBbkaoDSISoTqMcdwOcfvUPa'
  assert.equal(await verifyPassword('reactmap', legacy), true)
})

test('does not truncate passwords at 72 bytes', async () => {
  // bcrypt@5 silently truncated at 72 bytes, so 'a' * 73 and 'a' * 100 shared a
  // hash. Bun pre-hashes longer passwords instead, keeping every byte
  // significant. Guards against a regression to truncating behaviour.
  const hash = await hashPassword('a'.repeat(73))
  assert.equal(await verifyPassword('a'.repeat(73), hash), true)
  assert.equal(await verifyPassword('a'.repeat(72), hash), false)
  assert.equal(await verifyPassword('a'.repeat(100), hash), false)
})

// Fixtures below were generated by bcrypt@5.1.1 at cost 10 against the full
// password. bcrypt truncated at 72 bytes, so each hash encodes only that
// prefix, exactly as a row written before the Bun.password migration does.
const LEGACY_LONG_PASSWORD =
  'correct horse battery staple correct horse battery staple correct horse battery staple'
const LEGACY_LONG_HASH =
  '$2b$10$bx0gF1HY8Okg/KBBlwqtBOox.irY5bqaTEkR.OW8E8Xx3FRG8v.OS'

// 39 characters, 100 bytes. Byte 72 lands in the middle of a 3-byte 日, so a
// character-boundary slice and a lossy re-encode both produce different bytes
// than bcrypt saw.
const LEGACY_MULTIBYTE_PASSWORD = `p@sswörd-${'日'.repeat(30)}`
const LEGACY_MULTIBYTE_HASH =
  '$2b$10$bo6ga7lhKno/p//bkO6Bruz1JO2dJsHBjX0.AUWsnYkKRDWrUcAa6'

/**
 * Records every write to the users table so tests can assert none happens.
 * A legacy verify must never touch the stored hash.
 * @returns {{patch: object, column: string, value: unknown}[]}
 */
function trackUserUpdates() {
  /** @type {{patch: object, column: string, value: unknown}[]} */
  const updates = []
  state.db.models.User = {
    query: () => ({
      update: (patch) => ({
        where: (column, value) => {
          updates.push({ patch, column, value })
          return Promise.resolve(1)
        },
      }),
    }),
  }
  return updates
}

test('verifies a password longer than 72 bytes against its legacy hash', async () => {
  const updates = trackUserUpdates()
  assert.equal(
    await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH),
    true,
  )
  assert.equal(updates.length, 0)
})

test('does not rewrite the row for a login with a different tail', async () => {
  // The bytes past 72 were never verified against anything, so a mistyped tail
  // reaches this path looking exactly like the real one. Re-hashing the
  // submitted string would make the mistyped password canonical and lock the
  // owner out. The stored hash has to survive untouched.
  const updates = trackUserUpdates()
  const mistyped = `${LEGACY_LONG_PASSWORD.slice(0, 72)}totally different tail`
  assert.equal(Buffer.byteLength(mistyped, 'utf8') > 72, true)
  assert.notEqual(mistyped, LEGACY_LONG_PASSWORD)

  assert.equal(await verifyPassword(mistyped, LEGACY_LONG_HASH), true)

  assert.equal(updates.length, 0)
  // The real password still works, because nothing was written.
  assert.equal(
    await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH),
    true,
  )
})

test('keeps accepting the legacy prefix on every login', async () => {
  // Without the rewrite this path never converges, so it has to stay repeatable
  // rather than working once.
  const updates = trackUserUpdates()
  for (let i = 0; i < 3; ++i) {
    assert.equal(
      await verifyPassword(LEGACY_LONG_PASSWORD, LEGACY_LONG_HASH),
      true,
    )
  }
  assert.equal(updates.length, 0)
})

test('rejects a wrong password longer than 72 bytes', async () => {
  const updates = trackUserUpdates()
  const wrong = `wrong ${LEGACY_LONG_PASSWORD}`
  assert.equal(Buffer.byteLength(wrong, 'utf8') > 72, true)

  assert.equal(await verifyPassword(wrong, LEGACY_LONG_HASH), false)
  assert.equal(updates.length, 0)
})

test('truncates on the byte boundary, not the character boundary', async () => {
  const updates = trackUserUpdates()
  // Under 72 characters, so a length check would never reach the fallback.
  assert.equal(LEGACY_MULTIBYTE_PASSWORD.length < 72, true)
  assert.equal(Buffer.byteLength(LEGACY_MULTIBYTE_PASSWORD, 'utf8'), 100)

  assert.equal(
    await verifyPassword(LEGACY_MULTIBYTE_PASSWORD, LEGACY_MULTIBYTE_HASH),
    true,
  )
  assert.equal(updates.length, 0)
})

test('does not fall back for a hash written by Bun', async () => {
  const updates = trackUserUpdates()
  const hash = await hashPassword(LEGACY_LONG_PASSWORD)

  assert.equal(
    await verifyPassword(`${LEGACY_LONG_PASSWORD} extra`, hash),
    false,
  )
  assert.equal(updates.length, 0)

  const spy = spyOn(Bun.password, 'verify')
  try {
    assert.equal(await verifyPassword(LEGACY_LONG_PASSWORD, hash), true)
    assert.equal(spy.mock.calls.length, 1)
  } finally {
    spy.mockRestore()
  }
  assert.equal(updates.length, 0)
})
