const assert = require('node:assert/strict')
const { test } = require('bun:test')

require('./stateMock')
const { hashPassword, verifyPassword } = require('../src/services/LocalClient')

test('hashes a password into bcrypt format', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.match(hash, /^\$2[aby]\$/)
})

test('verifies a password it just hashed', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.equal(await verifyPassword('correct horse battery staple', hash), true)
})

test('rejects a wrong password', async () => {
  const hash = await hashPassword('correct horse battery staple')
  assert.equal(await verifyPassword('Tr0ub4dor&3', hash), false)
})

test('verifies a hash produced by the previous bcrypt library', async () => {
  // Generated by bcrypt@5.1.1 with cost 10 for the password "reactmap".
  const legacy = '$2b$10$aOiX/0v15RWQPR8q9hXl3.Z7HQgEYwBbkaoDSISoTqMcdwOcfvUPa'
  assert.equal(await verifyPassword('reactmap', legacy), true)
})

test('does not truncate passwords at 72 bytes', async () => {
  // bcrypt@5 silently truncated at 72 bytes, so 'a' * 73 and 'a' * 100 shared a
  // hash. Bun pre-hashes longer passwords instead, keeping every byte
  // significant. Guards against a regression to truncating behaviour.
  const hash = await hashPassword('a'.repeat(73))
  assert.equal(await verifyPassword('a'.repeat(73), hash), true)
  assert.equal(await verifyPassword('a'.repeat(72), hash), false)
  assert.equal(await verifyPassword('a'.repeat(100), hash), false)
})
