name: Sentry
on:
  release:
    types: [created, published, prereleased, released]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.11

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Sentry Build
        run: bun run release
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
